from tkinter import *
def golova():
    if golova==1:
        c.destroy()
tk = Tk()
fm=Frame(tk)
fm.pack(side=RIGHT)
c = Canvas(tk, width=1000, height=500, bg="white") 
c.create_oval((15,15,450,500))
c.create_oval((125,100,175,150))
c.create_oval((250,100,300,150))
c.create_arc((175,200,350,350))
c.create_arc((100,350,350,350), style=CHORD, start=0, extent=150)
c.pack(side=LEFT)
golova=Checkbutton(fm,text="Голова",font="Calibri 26", fg="green",variable=1,command=golova)
rot=Checkbutton(fm,text="Рот",font="Calibri 26", fg="green") 
nos=Checkbutton(fm,text="Нос",font="Calibri 26", fg="green") 
glaz=Checkbutton(fm,text="Глаз левый",font="Calibri 26", fg="green")
glaz2=Checkbutton(fm,text="Глаз правый",font="Calibri 26", fg="green")
golova.pack(side=RIGHT)
rot.pack(side=RIGHT)
nos.pack(side=RIGHT)
glaz.pack(side=RIGHT)
glaz2.pack(side=RIGHT)
tk.mainloop()